server:
  port: 7200

hibernate:
  hbm2ddl:
    auto: update
  cache:
    use_query_cache: false
    use_second_level_cache: false

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    properties:
      hibernate:
        id:
          new_generator_mappings: false
  datasource: # reporting
    jdbcUrl: jdbc:mysql://211.253.36.71:3306/reporting?useUnicode=true&charaterEncoding=utf-8
    username: root
    password: ksmartpia1!
  second-datasource: # wapi
    jdbcUrl: jdbc:mysql://ec2-54-180-141-141.ap-northeast-2.compute.amazonaws.com:3306/kspia_wapi_nonsan?useUnicode=true&charaterEncoding=utf-8
    username: root
    password: kspia01!@#
