server:
  port: 7001

hibernate:
  hbm2ddl:
    auto: update
  cache:
    use_query_cache: false
    use_second_level_cache: false

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    properties:
      hibernate:
        id:
          new_generator_mappings: false
  datasource: # wapi
    jdbcUrl: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS test
    username: sa
    password: sa
  second-datasource: # reporting
    jdbcUrl: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS test
    username: sa
    password: sa
